# 見た目のカスタム
remote_theme: tomjoht/documentation-theme-jekyll
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: ｺﾛｲﾄﾞのUnity拡張解説ページ
# this appears on the top navigation bar next to the home button

site_title: ｺﾛｲﾄﾞのUnity拡張
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: FUTEIKEI
# this appears in the footer

#github_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# gitlab_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using GitLab, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

google_analytics: 
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Jekyll documentation theme

feedback_email: circle.futeikei@gmail.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      search: true
      sidebar: home_sidebar
      topnav: topnav

  -
    scope:
      path: "BoneSelector"
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: BS_sidebar
      topnav: BS_topnav
  -
    scope:
      path: "BoneSelector"
      type: "posts"
    values:
      layout: "post"
      comments: false
      search: true
      sidebar: BS_sidebar
      topnav: BS_topnav

  -
    scope:
      path: "PBReplacer"
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: PBR_sidebar
      topnav: PBR_topnav

# these are defaults used for the frontmatter for these file types

sidebars:
- home_sidebar
- PBR_sidebar
- BS_sidebar